server:
  port: 8501
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/123123213
    username: tinywan
    password: 123456
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
